server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /


starling:
  account:
    path: api/v2/accounts
  feed:
    path: api/v2/feed/account/{accountId}/category/{categoryId}?changesSince={changesSinceTimestamp}
  baseUrl: https://api-sandbox.starlingbank.com/
  bearerToken: eyJhbGciOiJQUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAH1Uy5KbMBD8lS3OO1uAxcPccssP5ANG0shWGSRKEk62Uvn3CATGOFu5ubvn0TMj_DvT3mddhqMGSYP98AFdr82Fo7l9CDtk75mfeIyQ1Cp-whJUVSpgkjXAsRCgzqqqmCpVW8gYTL_GrCuqMyvzM2PNe6YxJKIoT_lMoBB2MuG77SW5H1rG2m2d13WtGihFUQM7sRMgEzm0eVWwRmEjWRVrB3sjkzLqNpcqJ4SKlwxYySVwlp-gVWfeRJFXnMWMONY3Icj7lFUUXBGVCEqhBCYkB16rMzBsoz1SjRA4DyzsSPNSklO4LlbB4ECdI5RvL0L4HF8ELckErTS5I99rHw7MCqR00WRHUocHSEoIKK4DPSJ3_NPpQG84hat12seTgTZS37WcsE_BHHs0YrUm0EkQ1gRn-9RoZlbNGqXdgEFbA1aBmoz0D8k_um8gtRaTD3bYRqQB9Vq4p2jEXDocx_7zgZaoAY3EQJ2knmKJDa6au1GYBxkdKXIUvfv_SclG0sYeBcUNBLq4ZY7nxH_FNZWcuOI23UABoxvsRISLuuJlqBE_iTYpgXWIBPYg0ANe1pmStv-E4NB4FLvDSAOf-lu3XZJ2au-W8N4w4UeB3op49KfwhQA7X_-VXbOcVbrfvCbzB2qJciRIj-EA_FFKm_R4j9fxcLG7jwO3Wj9wS51nJm0n3verErv4Ra1dTEXFleTUk4Q49v71eAohDjiNKxxx-zri397ySsE6-dT-yG59j-yWH2huBMLfX6lRqpWauBcubm2-_lbtmVuinp_IcpjXN5P9-QtxqeyktwUAAA.OtXRQ5tDbtsf_RNeyY0PMYnMXXne-lx6FMYxQUm7ol41ufUCfJFFJg74n1_0nArI2uTx1UTaAIHHZGow1rn_p1t1QsxQPD65i6UI4I0SOVNUeyp2wqe95gn9q_qilpSKjEBqJYznaYowofBZpK8ot1hc8E7e4FkGVq-p1dyLIXJQm8fv4WrKFz5RuGlC1PLwZ1rwp_l-M94Me3s8-6h7lEdjSvYLIjzHUtEy_bQ_se2GkJFREfxOpQErEn2JmKyDRymDZSR27KIA0eo0GD7gik5i85tm_L9E3Y_2tY9zb5llr9rBatQgU2tp8JL3BeQrewbjknOpvDJiHF0bI374jBVjFOXLzUd6Av06AKWMX0b-QkI1ex-MyE8odzasC4fIz1pQd6Rb5RIPJdqGShM7ZRjSs56TkrCYYoKWwc2lsGStxnctEioup-SLmE0M-E6c5Pvbn02frUq2rPTxCEn_04plD_KfiIp3IYVovbrKWKy_ogt1_3zy7SiQToRDPI7N-k4W7A8XyW1J0R79LP-M139qExgisJJh3I6BBp-u_KxpG0oQZ-PPfkaFB8ui4KNFYy1dPmqBIOARqvgtVHPrIVRBvUIavNMDNnLbRdsI6pCEY9fevBxj5d5Ye-WU0YwzPCek1ClelPBlJQklvQ35HY5KwWpcnGVpxcd3A65oBGU