name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: lint
      run: ./gradlew verifyGoogleJavaFormat
    - name: test
      run: ./gradlew test
    - name: build-jar
      run: ./gradlew build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1 
      with:
        name: starling-roundup.jar
        path: build/libs/starling-roundup.jar
    - name: build-container
      run: docker build -t starling-roundup .
